import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Scheme from '../src/models/Scheme.js';

dotenv.config();

const schemes = [
  {
    name: 'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (PM-JAY)',
    issuer: 'Central',
    category: 'health',
    shortDescription: 'Free health coverage up to ₹5 Lakhs per family per year for secondary and tertiary care hospitalization.',
    fullDescription: 'Ayushman Bharat PM-JAY is the largest health assurance scheme in the world, which aims to provide a health cover of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization to over 12 crores poor and vulnerable families (approximately 55 crore beneficiaries). The scheme provides cashless access to health care services for the beneficiary at the point of service, i.e., the hospital.',
    eligibility: {
      minAge: 0,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 150000,
      occupation: ['any'],
      applicableStates: ['any'],
    },
    benefits: [
      'Cashless treatment up to ₹5,00,000 per family per year.',
      'No cap on family size, age, or gender.',
      'Pre-existing diseases are covered from day one.',
      'Includes pre and post-hospitalization expenses up to 15 days.',
    ],
    documentsRequired: [
      'Aadhaar Card or Voter ID',
      'Ration Card / PM-JAY Letter',
      'Income Certificate',
      'Caste Certificate (if applicable)',
    ],
    applicationSteps: [
      'Check eligibility online or at PM-JAY kiosk.',
      'Visit any empaneled government or private hospital.',
      'Contact the Ayushman Mitra or help desk at the hospital.',
      'Show your Aadhaar/Ration card to verify identity.',
      'Avail cashless diagnostics, treatment, and medications.',
    ],
    officialLink: 'https://pmjay.gov.in',
  },
  {
    name: 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
    issuer: 'Central',
    category: 'life',
    shortDescription: 'One-year term life insurance scheme offering ₹2 Lakhs cover for death due to any cause.',
    fullDescription: 'PMJJBY is a government-backed life insurance scheme in India. It is a one-year life insurance scheme, renewable from year to year, offering coverage for death due to any cause. The premium is automatically debited from the bank account of the subscriber.',
    eligibility: {
      minAge: 18,
      maxAge: 50,
      gender: 'any',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['any'],
      applicableStates: ['any'],
    },
    benefits: [
      'Term insurance cover of ₹2,00,000 in case of death of the subscriber.',
      'Affordable annual premium of ₹436.',
      'Easy automatic enrollment and debit via linked bank account.',
    ],
    documentsRequired: [
      'Aadhaar Card',
      'Bank Account Passbook',
      'Consent form for auto-debit',
    ],
    applicationSteps: [
      'Visit your bank branch where you hold a savings account.',
      'Fill out the PMJJBY registration/consent form.',
      'Ensure sufficient balance for the automatic premium debit.',
      'Receive the policy certificate online or via SMS.',
    ],
    officialLink: 'https://www.jansuraksha.gov.in',
  },
  {
    name: 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
    issuer: 'Central',
    category: 'accident',
    shortDescription: 'Accidental death and disability insurance cover of ₹2 Lakhs for just ₹20 per year.',
    fullDescription: 'PMSBY is a government-backed accident insurance scheme in India. It is available to people between 18 and 70 years of age with bank accounts. It provides a death or total disability cover of ₹2 lakhs and partial disability cover of ₹1 lakh.',
    eligibility: {
      minAge: 18,
      maxAge: 70,
      gender: 'any',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['any'],
      applicableStates: ['any'],
    },
    benefits: [
      'Death benefit of ₹2,00,000 for accidental death.',
      'Total and irrecoverable loss of both eyes or loss of use of both hands or feet: ₹2,00,000.',
      'Loss of one eye or loss of use of one hand or foot: ₹1,00,000.',
      'Extremely low premium of ₹20 per annum.',
    ],
    documentsRequired: [
      'Aadhaar Card',
      'Savings Bank Account details',
      'Nominee details and KYC',
    ],
    applicationSteps: [
      'Access your mobile banking app or visit your bank branch.',
      'Select the PMSBY enrollment options.',
      'Submit auto-debit authorization form.',
      'Verify details and submit the application.',
    ],
    officialLink: 'https://www.jansuraksha.gov.in',
  },
  {
    name: 'Atal Pension Yojana (APY)',
    issuer: 'Central',
    category: 'pension',
    shortDescription: 'Guaranteed pension scheme from ₹1,000 to ₹5,000 per month after the age of 60.',
    fullDescription: 'APY is a pension scheme for citizens of India focused on unorganized sector workers. Under the APY, a guaranteed minimum pension of ₹1,000 to ₹5,000 per month will be given at the age of 60 years, depending on the contributions made by the subscriber.',
    eligibility: {
      minAge: 18,
      maxAge: 40,
      gender: 'any',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['any'],
      applicableStates: ['any'],
    },
    benefits: [
      'Guaranteed monthly pension of ₹1,000, ₹2,000, ₹3,000, ₹4,000, or ₹5,000 after age 60.',
      'In case of death of the subscriber, the spouse receives the pension.',
      'In case of death of both, the nominee receives the accumulated corpus.',
    ],
    documentsRequired: [
      'Aadhaar Card',
      'Active Mobile Number',
      'Bank Account linked with Aadhaar',
    ],
    applicationSteps: [
      'Approach the bank/post office where your savings account is held.',
      'Fill APY registration form with nominee and spouse details.',
      'Choose your pension tier amount.',
      'Set up auto-debit for monthly/quarterly/half-yearly contributions.',
    ],
    officialLink: 'https://www.npscra.nsdl.co.in',
  },
  {
    name: 'Sukanya Samriddhi Yojana (SSY)',
    issuer: 'Central',
    category: 'life',
    shortDescription: 'Dedicated savings scheme for the girl child offering high interest rates and tax exemptions.',
    fullDescription: 'SSY is a government-backed savings scheme targeted at the parents of girl children. The scheme encourages parents to build a fund for the future education and marriage expenses of their female child. It offers high interest rates and tax benefits under Section 80C.',
    eligibility: {
      minAge: 0,
      maxAge: 10,
      gender: 'female',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['student'],
      applicableStates: ['any'],
    },
    benefits: [
      'Higher interest rate compared to other small savings schemes.',
      'Tax deduction benefit under Section 80C of IT Act.',
      'Triple tax-exempt (EEE status): Principal, interest, and maturity are tax-free.',
      'Long-term savings option; account matures after 21 years.',
    ],
    documentsRequired: [
      'Birth Certificate of the girl child',
      'Aadhaar Card / PAN of the parent/guardian',
      'Address Proof',
      'Passport size photos',
    ],
    applicationSteps: [
      'Visit any authorized post office branch or commercial bank.',
      'Request the Sukanya Samriddhi Account opening form.',
      'Submit the child\'s birth certificate and guardian KYC documents.',
      'Pay the initial deposit amount (minimum ₹250).',
    ],
    officialLink: 'https://www.indiapost.gov.in',
  },
  {
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    issuer: 'Central',
    category: 'crop',
    shortDescription: 'Comprehensive crop insurance covering yield losses due to natural calamities, pests, and diseases.',
    fullDescription: 'PMFBY is a crop insurance scheme launched by the government of India. It aims to support sustainable production in agriculture sector by providing financial support to farmers suffering crop loss/damage arising out of natural calamities.',
    eligibility: {
      minAge: 18,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['farmer'],
      applicableStates: ['any'],
    },
    benefits: [
      'Low premium rates (1.5% to 2% for food crops, 5% for commercial/horticultural crops).',
      'Full insurance cover for all food, oilseeds, and commercial crops.',
      'Cashless direct bank transfer of claim settlements.',
    ],
    documentsRequired: [
      'Land Ownership / Tenant documents',
      'Sowing Certificate',
      'Aadhaar Card',
      'Bank Passbook photocopy',
    ],
    applicationSteps: [
      'Access the National Crop Insurance Portal (NCIP) or visit a local cooperative bank.',
      'Register as a farmer and submit land surveys.',
      'Pay the subsidized farmer premium share.',
      'Keep records of sowing and inspections.',
    ],
    officialLink: 'https://pmfby.gov.in',
  },
  {
    name: 'National Pension System (NPS)',
    issuer: 'Central',
    category: 'pension',
    shortDescription: 'Flexible pension and long-term retirement savings scheme with professional fund management.',
    fullDescription: 'The National Pension System is a voluntary defined contribution pension system in India. NPS is managed by the Pension Fund Regulatory and Development Authority (PFRDA). It offers market-linked returns and flexible investment options for professionals and salaried individuals.',
    eligibility: {
      minAge: 18,
      maxAge: 70,
      gender: 'any',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['professional', 'any'],
      applicableStates: ['any'],
    },
    benefits: [
      'Additional tax benefit up to ₹50,000 under Section 80CCD(1B).',
      'Choice of active or auto investment asset allocation.',
      'Portable account structure across different jobs and cities via PRAN.',
    ],
    documentsRequired: [
      'Aadhaar Card',
      'PAN Card',
      'Bank Account proof (cancelled cheque)',
      'Digital signature and photo',
    ],
    applicationSteps: [
      'Visit the eNPS official registration portal.',
      'Choose Tier-I or Tier-II account structure.',
      'Verify KYC details using Aadhaar OTP.',
      'Make the initial payment of minimum ₹500.',
      'Get your PRAN card generated.',
    ],
    officialLink: 'https://www.npstrust.org.in',
  },
  {
    name: 'Senior Citizens Savings Scheme (SCSS)',
    issuer: 'Central',
    category: 'pension',
    shortDescription: 'Secure, government-backed savings avenue for individuals above 60 years offering quarterly interest.',
    fullDescription: 'SCSS is a government-backed retirement benefits program. Senior citizens resident in India can make a lump-sum deposit in the scheme, which offers safety, tax saving benefits, and guaranteed regular income with quarterly payouts.',
    eligibility: {
      minAge: 60,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['any'],
      applicableStates: ['any'],
    },
    benefits: [
      'High guaranteed interest rates paid out quarterly.',
      'Maturity period of 5 years, extendable by another 3 years.',
      'Investments qualify for tax deduction under Section 80C.',
      'Maximum investment limit up to ₹30 Lakhs.',
    ],
    documentsRequired: [
      'Age proof (PAN card, Passport, Birth Certificate)',
      'Aadhaar Card',
      'Address Proof',
      'Recent photographs',
    ],
    applicationSteps: [
      'Visit a designated post office or public sector bank branch.',
      'Fill out the SCSS Account opening form.',
      'Provide self-attested copies of age proof and KYC documents.',
      'Deposit the capital amount in cash, cheque, or demand draft.',
    ],
    officialLink: 'https://www.nsiindia.gov.in',
  },
  {
    name: 'Pudhumai Penn Scheme',
    issuer: 'Tamil Nadu',
    category: 'education',
    shortDescription: 'Tamil Nadu scheme offering ₹1,000/month for girl students from government schools pursuing higher education.',
    fullDescription: 'Under the Moovalur Ramamirtham Ammaiyar Higher Education Assurance Scheme (Pudhumai Penn), all girl students who studied from classes 6 to 12 in Tamil Nadu government schools are eligible to receive ₹1,000 per month for their higher studies (Diploma, Degree, ITI) till completion.',
    eligibility: {
      minAge: 17,
      maxAge: 25,
      gender: 'female',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['student'],
      applicableStates: ['Tamil Nadu'],
    },
    benefits: [
      'Monthly financial assistance of ₹1,000 directly transferred to bank accounts.',
      'Covers duration of undergraduate degree, diploma, or ITI programs.',
      'Encourages reduction in dropouts among female students.',
    ],
    documentsRequired: [
      'School Transfer Certificate showing classes 6 to 12 in Govt schools',
      'Aadhaar Card',
      'Active College Admission card',
      'Bank Account details with passbook',
    ],
    applicationSteps: [
      'Register via the designated Pudhumai Penn web portal at college.',
      'Submit school educational certificates to college coordinator.',
      'Verify bank details linked to student Aadhaar number.',
      'Await approval from Tamil Nadu Social Welfare department.',
    ],
    officialLink: 'https://www.pudhumapenn.tn.gov.in',
  },
  {
    name: 'Kalaignar Magalir Urimai Thittam',
    issuer: 'Tamil Nadu',
    category: 'other',
    shortDescription: 'Basic income support of ₹1,000 per month to eligible female heads of families in Tamil Nadu.',
    fullDescription: 'Kalaignar Magalir Urimai Thittam is a social welfare scheme in Tamil Nadu that provides basic financial assistance of ₹1,000 per month to eligible female heads of households. It aims to support livelihood and reduce poverty among low-income families.',
    eligibility: {
      minAge: 21,
      maxAge: 100,
      gender: 'female',
      minIncome: 0,
      maxIncome: 250000,
      occupation: ['any'],
      applicableStates: ['Tamil Nadu'],
    },
    benefits: [
      'Monthly cash transfer of ₹1,000 directly to the family head\'s bank account.',
      'Financial independence for women in economically weaker sections.',
    ],
    documentsRequired: [
      'Ration Card (Smart card)',
      'Aadhaar Card',
      'Bank Passbook / account details',
      'Income Certificate',
    ],
    applicationSteps: [
      'Collect application forms at designated ration shops.',
      'Fill up details and attend verification camps in your locality.',
      'Verify fingerprint/biometrics if required.',
      'Direct credit starts post checking ration and income criteria.',
    ],
    officialLink: 'https://www.tn.gov.in',
  },
  {
    name: 'Pradhan Mantri Awas Yojana - Urban (PMAY-U)',
    issuer: 'Central',
    category: 'housing',
    shortDescription: 'Credit-linked subsidy and financial assistance for purchasing or constructing affordable houses.',
    fullDescription: 'Pradhan Mantri Awas Yojana - Urban is a flagship Mission of the Government of India implemented by the Ministry of Housing and Urban Affairs (MoHUA). It addresses urban housing shortage among the EWS/LIG and MIG categories by ensuring a pucca house to all eligible urban families.',
    eligibility: {
      minAge: 18,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 1800000,
      occupation: ['any'],
      applicableStates: ['any'],
    },
    benefits: [
      'Interest subsidy up to 6.5% on home loans under Credit Linked Subsidy Scheme (CLSS).',
      'Direct central assistance of ₹1.5 Lakhs for construction of homes.',
      'Preference to women, seniors, and differently-abled individuals.',
    ],
    documentsRequired: [
      'Aadhaar Card',
      'Income Certificate / Salary slips',
      'Affidavit stating the family does not own any pucca house in India',
      'Land ownership documents (if applicable)',
    ],
    applicationSteps: [
      'Register on the official PMAY portal under citizen assessment.',
      'Select the benefit category (e.g. Subsidy, In-situ redevelopment).',
      'Fill out the applicant details and bank account numbers.',
      'Submit the form and track application status online.',
    ],
    officialLink: 'https://pmay-urban.gov.in',
  },
  {
    name: 'Pradhan Mantri Shram Yogi Maan-dhan (PM-SYM)',
    issuer: 'Central',
    category: 'pension',
    shortDescription: 'Voluntary pension scheme for unorganized workers offering ₹3,000 monthly pension.',
    fullDescription: 'PM-SYM is a voluntary and co-contributory pension scheme for unorganized workers (like street vendors, rickshaw pullers, construction workers, etc.) in the age group of 18-40 years. It offers a monthly pension of ₹3,000 after completing 60 years.',
    eligibility: {
      minAge: 18,
      maxAge: 40,
      gender: 'any',
      minIncome: 0,
      maxIncome: 180000,
      occupation: ['farmer', 'any'],
      applicableStates: ['any'],
    },
    benefits: [
      'Assured monthly pension of ₹3,000 after attaining 60 years.',
      'Equal co-contribution by the Central Government.',
      'Spouse receives 50% of the pension in case of death of the pensioner.',
    ],
    documentsRequired: [
      'Aadhaar Card',
      'Savings Bank Account details (IFSC, Account Number)',
      'Mobile Number',
    ],
    applicationSteps: [
      'Visit your nearest Common Services Centre (CSC).',
      'Give self-declaration of unorganized sector work.',
      'Complete biometric verification using Aadhaar.',
      'First contribution is paid in cash, then auto-debited monthly.',
    ],
    officialLink: 'https://maandhan.in',
  },
  {
    name: 'PM Kisan Samman Nidhi (PM-KISAN)',
    issuer: 'Central',
    category: 'crop',
    shortDescription: 'Direct income support of ₹6,000 per year paid in three equal installments to all landholding farmer families.',
    fullDescription: 'PM-KISAN is a central sector scheme that provides income support to all landholding farmer families across the country to enable them to take care of expenses related to agriculture and allied activities as well as domestic needs.',
    eligibility: {
      minAge: 18,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['farmer'],
      applicableStates: ['any'],
    },
    benefits: [
      'Direct cash benefit of ₹6,000 per year, paid in three installments of ₹2,000 each.',
      'Direct bank transfer ensuring zero leakages.',
    ],
    documentsRequired: [
      'Landholding documents / Land cultivation certificates',
      'Aadhaar Card',
      'Bank Account details',
      'Citizenship certificate',
    ],
    applicationSteps: [
      'Self-register on the PM-Kisan portal or visit local CSC centers.',
      'Input personal identity and land records.',
      'Verify details via e-KYC using Aadhaar OTP.',
      'State Nodal officers verify the land records to approve direct payouts.',
    ],
    officialLink: 'https://pmkisan.gov.in',
  },
  {
    name: 'Gruha Lakshmi Scheme (Karnataka)',
    issuer: 'Karnataka',
    category: 'other',
    shortDescription: 'Karnataka government scheme providing ₹2,000/month financial aid to female heads of families.',
    fullDescription: 'Gruha Lakshmi is one of the five guarantee schemes of the Karnataka state government. It aims to support women empowerment and improve financial status of families by providing a direct cash benefit of ₹2,000 monthly to the woman designated as head of the family.',
    eligibility: {
      minAge: 18,
      maxAge: 100,
      gender: 'female',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['any'],
      applicableStates: ['Karnataka'],
    },
    benefits: [
      'Monthly direct transfer of ₹2,000 to the woman head of household.',
      'Assists families in coping with inflation and daily expenditures.',
    ],
    documentsRequired: [
      'Ration Card / BPL card copy',
      'Aadhaar Cards of husband and wife',
      'Mobile number linked with Aadhaar',
      'Bank Account Passbook copy',
    ],
    applicationSteps: [
      'Register at Karnataka One, Bangalore One, or Grama One centers.',
      'Provide Ration card details to locate family records.',
      'Submit KYC and verify bank accounts.',
      'Receive registration acknowledgment receipt.',
    ],
    officialLink: 'https://sevasindhu.karnataka.gov.in',
  },
  {
    name: 'Rythu Bandhu Scheme (Telangana)',
    issuer: 'Telangana',
    category: 'crop',
    shortDescription: 'Farmers Investment Support Scheme offering ₹10,000 per acre per year for agricultural inputs.',
    fullDescription: 'Rythu Bandhu scheme also known as Farmers Investment Support Scheme is a welfare program to support farmer investment for two crops a year by the Government of Telangana. The government provides financial assistance directly to all landowning farmers.',
    eligibility: {
      minAge: 18,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['farmer'],
      applicableStates: ['Telangana'],
    },
    benefits: [
      'Financial grant of ₹5,000 per acre per season (total ₹10,000 per year) for inputs like seeds, fertilizers, pesticides, and labor.',
      'No cap on maximum acres owned.',
    ],
    documentsRequired: [
      'Pattadar Passbook (Land ownership book)',
      'Aadhaar Card',
      'Bank Account Passbook details',
    ],
    applicationSteps: [
      'Register and submit Pattadar passbook details to Agriculture Extension Officers (AEOs).',
      'AEOs carry out physical verification of land ownership.',
      'Approved database is sent to banks for direct treasury transfers.',
    ],
    officialLink: 'https://rythubandhu.telangana.gov.in',
  },
  {
    name: 'Ladli Behna Yojana (Madhya Pradesh)',
    issuer: 'Madhya Pradesh',
    category: 'other',
    shortDescription: 'Financial assistance of ₹1,250 per month to married women in Madhya Pradesh.',
    fullDescription: 'Mukhyamantri Ladli Behna Yojana is a state-level social welfare scheme in Madhya Pradesh. It targets women in low-income families and provides direct financial assistance to promote health, nutrition, and financial independence.',
    eligibility: {
      minAge: 21,
      maxAge: 60,
      gender: 'female',
      minIncome: 0,
      maxIncome: 250000,
      occupation: ['any'],
      applicableStates: ['Madhya Pradesh'],
    },
    benefits: [
      'Monthly payment of ₹1,250 credited directly to bank accounts.',
      'Supports female education, nutrition, and household support.',
    ],
    documentsRequired: [
      'Samagra Family ID',
      'Aadhaar Card',
      'Ration Card / BPL card details',
      'Active bank account linked with Aadhaar',
    ],
    applicationSteps: [
      'Attend the registration camps organized in local panchayats/wards.',
      'Fill up the application forms with Samagra ID details.',
      'Submit biometrics and take photos for verification.',
      'Approved applications list is published locally.',
    ],
    officialLink: 'https://cmladlibahna.mp.gov.in',
  },
  {
    name: 'Kanyashree Prakalpa (West Bengal)',
    issuer: 'West Bengal',
    category: 'education',
    shortDescription: 'Conditional cash transfer scheme to prevent early marriage and support girl child education.',
    fullDescription: 'Kanyashree Prakalpa is a conditional cash transfer scheme implemented by the Government of West Bengal. It aims to improve the status and well-being of girls, specifically from low-income families, by incentivizing secondary education and preventing early marriage.',
    eligibility: {
      minAge: 13,
      maxAge: 19,
      gender: 'female',
      minIncome: 0,
      maxIncome: 120000,
      occupation: ['student'],
      applicableStates: ['West Bengal'],
    },
    benefits: [
      'Annual scholarship of ₹1,000 for girls between 13 and 18 years (K1 tier).',
      'One-time grant of ₹25,000 upon reaching 18 years if unmarried and in school/college (K2 tier).',
      'Financial support for academic fees and stationeries.',
    ],
    documentsRequired: [
      'School Certificate / Enrollment proof',
      'Declaration form confirming unmarried status',
      'Income Certificate copy',
      'Aadhaar Card copy',
    ],
    applicationSteps: [
      'Obtain Kanyashree application forms at your school or college.',
      'Fill the form with student details and bank account numbers.',
      'School headmaster verifies enrollment and forwards application to District Welfare officer.',
      'Sanctioned scholarship is transferred directly to bank account.',
    ],
    officialLink: 'https://www.wbkanyashree.gov.in',
  },
  {
    name: 'Central Sector Scheme of Scholarship for College Students',
    issuer: 'Central',
    category: 'education',
    shortDescription: 'Scholarship of up to ₹20,000 per year for meritorious students from low-income families pursuing higher studies.',
    fullDescription: 'The scheme provides financial assistance to meritorious students from poor families to meet a part of their day-to-day expenses while pursuing higher studies (graduation, post-graduation, professional courses).',
    eligibility: {
      minAge: 17,
      maxAge: 25,
      gender: 'any',
      minIncome: 0,
      maxIncome: 450000,
      occupation: ['student'],
      applicableStates: ['any'],
    },
    benefits: [
      '₹12,000 per annum for the first three years of graduation.',
      '₹20,000 per annum for post-graduation and professional courses.',
      'Broadly covers cost of college fees and books.',
    ],
    documentsRequired: [
      '12th standard mark sheet showing above 80th percentile',
      'Income Certificate of parents',
      'Aadhaar Card',
      'College Admission Fee receipt',
    ],
    applicationSteps: [
      'Apply online on the National Scholarship Portal (NSP).',
      'Select Central Sector Scheme of Scholarship.',
      'Upload academic transcripts and parent income certificate.',
      'College validates and submits verification to Ministry of Education.',
    ],
    officialLink: 'https://scholarships.gov.in',
  },
  {
    name: 'Sanjay Gandhi Niradhar Grant Scheme',
    issuer: 'Maharashtra',
    category: 'pension',
    shortDescription: 'Financial assistance of ₹1,000 to ₹1,500 per month for destitutes and differently-abled individuals in Maharashtra.',
    fullDescription: 'This state scheme in Maharashtra provides financial assistance to old age people, destitutes, differently-abled persons, widows, and people suffering from major illnesses, who have no source of income.',
    eligibility: {
      minAge: 18,
      maxAge: 64,
      gender: 'any',
      minIncome: 0,
      maxIncome: 21000,
      occupation: ['any'],
      applicableStates: ['Maharashtra'],
    },
    benefits: [
      'Monthly grant of ₹1,000 for single person households.',
      'Monthly grant of ₹1,500 for households with multiple eligible members.',
      'Livelihood support for underprivileged citizens.',
    ],
    documentsRequired: [
      'Age proof / Birth Certificate',
      'Income Certificate (below ₹21,000/yr)',
      'Domicile Certificate of Maharashtra',
      'Medical certificate of disability (if applicable)',
    ],
    applicationSteps: [
      'Apply at the local Collector\'s office or Tahsildar office.',
      'Submit the filled-in physical application with domicile documents.',
      'Verification is done by local village or municipal officers.',
      'Grants are disbursed monthly via post office or bank account.',
    ],
    officialLink: 'https://mahasarkar.co.in',
  },
  {
    name: 'Mukhyamantri Amrutum Yojana (MA)',
    issuer: 'Gujarat',
    category: 'health',
    shortDescription: 'Gujarat tertiary health assurance scheme providing free hospitalization up to ₹3 Lakhs to BPL families.',
    fullDescription: 'Mukhyamantri Amrutum Yojana is a tertiary health care scheme launched by the Government of Gujarat for Below Poverty Line (BPL) and lower-middle-class families. It covers treatment expenses for serious illnesses requiring surgery and hospitalization.',
    eligibility: {
      minAge: 0,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 400000,
      occupation: ['any'],
      applicableStates: ['Gujarat'],
    },
    benefits: [
      'Free cashless hospitalization up to ₹3,00,000 per family per year.',
      'Covers major surgical procedures like cardiology, neurology, and oncology.',
      'Travel allowance of ₹300 per hospital visit to beneficiaries.',
    ],
    documentsRequired: [
      'Gujarat BPL card copy / Income Certificate (below ₹4L/yr)',
      'Aadhaar Cards of all family members',
      'Address proof in Gujarat',
    ],
    applicationSteps: [
      'Visit a district kiosk or designated civic center in Gujarat.',
      'Scan biometrics of all family members to enroll.',
      'Receive the MA Smart Card.',
      'Produce MA Card at any empaneled hospital for cashless treatment.',
    ],
    officialLink: 'https://magujarat.in',
  },
  {
    name: 'Biju Swasthya Kalyan Yojana (BSKY)',
    issuer: 'Odisha',
    category: 'health',
    shortDescription: 'Odisha state health assurance scheme providing ₹5 Lakhs (₹10 Lakhs for women) coverage in top hospitals.',
    fullDescription: 'BSKY is a pathbreaking health assurance initiative by the Government of Odisha. It provides health coverage up to ₹5 lakhs per family per year for male/general members, and up to ₹10 lakhs per year for female members for secondary and tertiary care.',
    eligibility: {
      minAge: 0,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 600000,
      occupation: ['any'],
      applicableStates: ['Odisha'],
    },
    benefits: [
      'Cashless care in empaneled private hospitals up to ₹5 Lakhs for males and ₹10 Lakhs for female family members.',
      'All diagnostics and treatment costs are covered.',
    ],
    documentsRequired: [
      'Ration Card / NFSA / SFSS Card',
      'Aadhaar Cards of all members',
      'Domicile certificate in Odisha',
    ],
    applicationSteps: [
      'All NFSA/SFSS beneficiaries in Odisha are automatically enrolled.',
      'Collect BSKY Health Cards from local distribution counters.',
      'Submit BSKY card at empaneled hospitals during admission.',
    ],
    officialLink: 'https://bsky.odisha.gov.in',
  },
  {
    name: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
    issuer: 'Central',
    category: 'health',
    shortDescription: 'Maternity benefit scheme offering ₹5,000 cash incentive to pregnant and lactating mothers.',
    fullDescription: 'PMMVY is a conditional cash transfer scheme for pregnant and lactating women. It provides partial compensation for wage loss in terms of cash incentives so that the woman can take adequate rest before and after delivery of her first living child.',
    eligibility: {
      minAge: 19,
      maxAge: 100,
      gender: 'female',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['any'],
      applicableStates: ['any'],
    },
    benefits: [
      'Cash incentive of ₹5,000 paid in three installments (₹1000, ₹2000, ₹2000) linked to health checkpoints.',
      'Encourages institutional deliveries and immunizations.',
    ],
    documentsRequired: [
      'Mother and Child Protection (MCP) Card copy',
      'Identity Proof (Aadhaar Card)',
      'Bank Account Passbook copy',
      'Husband\'s Aadhaar Card copy',
    ],
    applicationSteps: [
      'Register at your nearest Anganwadi Centre (AWC) or healthcare center.',
      'Submit Form 1A along with MCP card copies for first installment.',
      'Submit Form 1B after completing antenatal checkup for second installment.',
      'Submit Form 1C post childbirth and first cycle of vaccination.',
    ],
    officialLink: 'https://wcd.gov.in',
  },
  {
    name: 'Post Office Monthly Income Scheme (POMIS)',
    issuer: 'Central',
    category: 'pension',
    shortDescription: 'Safe, fixed-income investment scheme offering monthly interest payouts with zero market risks.',
    fullDescription: 'POMIS is a popular saving scheme backed by the Ministry of Finance. It enables investors to block a capital sum and receive fixed monthly interest payments, making it ideal for retirees or risk-averse individuals.',
    eligibility: {
      minAge: 10,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['any'],
      applicableStates: ['any'],
    },
    benefits: [
      'Regular monthly interest payout credited to linked savings account.',
      'Highly safe as it is backed directly by the Indian Government.',
      'Minimum investment of ₹1,000; maximum up to ₹9 Lakhs (individual) or ₹15 Lakhs (joint).',
    ],
    documentsRequired: [
      'KYC documents (Aadhaar, Voter ID, PAN Card)',
      'Address Proof',
      'Passport size photographs',
      'Nomination details form',
    ],
    applicationSteps: [
      'Visit any post office branch.',
      'Complete the POMIS Account opening form.',
      'Submit KYC photocopies.',
      'Pay the deposit amount through cash or cheque.',
    ],
    officialLink: 'https://www.indiapost.gov.in',
  },
  {
    name: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
    issuer: 'Central',
    category: 'other',
    shortDescription: 'National mission for financial inclusion offering zero-balance accounts, overdraft, and debit card benefits.',
    fullDescription: 'PMJDY is national mission for financial inclusion to ensure access to financial services, namely, basic savings bank account, remittance, credit, insurance, pension in an affordable manner.',
    eligibility: {
      minAge: 10,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['any'],
      applicableStates: ['any'],
    },
    benefits: [
      'No minimum balance required for savings accounts.',
      'Accident insurance cover of ₹2 Lakhs with RuPay debit cards.',
      'Overdraft facility up to ₹10,000 for eligible account holders.',
      'Direct benefit transfer (DBT) credit from government schemes.',
    ],
    documentsRequired: [
      'Aadhaar Card or Voter ID card',
      'PAN Card (if available)',
      'Address proof',
      'Passport photographs',
    ],
    applicationSteps: [
      'Visit any bank branch or authorized Bank Mitra (Business Correspondent).',
      'Fill up the Jan Dhan account opening form.',
      'Submit copies of Aadhaar card for KYC verification.',
      'Receive the zero-balance account number and RuPay card.',
    ],
    officialLink: 'https://pmjdy.gov.in',
  },
  {
    name: 'Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)',
    issuer: 'Central',
    category: 'other',
    shortDescription: 'Labor law guaranteeing 100 days of wage employment per year to rural households.',
    fullDescription: 'MGNREGA is a social security measure that aims to guarantee the right to work. It provides at least 100 days of guaranteed wage employment in a financial year to every rural household whose adult members volunteer to do unskilled manual work.',
    eligibility: {
      minAge: 18,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 999999999,
      occupation: ['farmer', 'any'],
      applicableStates: ['any'],
    },
    benefits: [
      'Guaranteed 100 days of wage employment.',
      'Unemployment allowance if work is not provided within 15 days of application.',
      'Direct wage credit to savings accounts.',
    ],
    documentsRequired: [
      'Aadhaar Card',
      'Ration Card copy',
      'Bank Account details',
      'Residential proof in Gram Panchayat',
    ],
    applicationSteps: [
      'Submit registration form to the local Gram Panchayat.',
      'Gram Panchayat issues a MGNREGA Job Card to the household.',
      'Submit a written request for employment stating dates and duration.',
      'Gram Panchayat assigns manual civil work locally.',
    ],
    officialLink: 'https://nrega.nic.in',
  },
  {
    name: 'Rashtriya Swasthya Bima Yojana (RSBY)',
    issuer: 'Central',
    category: 'health',
    shortDescription: 'Subsidized health insurance cover of ₹30,000 for unorganized sector BPL workers.',
    fullDescription: 'RSBY is a government-run health insurance programme for the Indian poor. It provides cashless insurance cover for hospitalization in empaneled hospitals. It was primarily designed to protect BPL workers in the unorganized sector from catastrophic health shocks.',
    eligibility: {
      minAge: 18,
      maxAge: 100,
      gender: 'any',
      minIncome: 0,
      maxIncome: 120000,
      occupation: ['any'],
      applicableStates: ['any'],
    },
    benefits: [
      'Cashless treatment in empaneled hospitals up to ₹30,000 per family per year.',
      'Covers pre-existing diseases.',
      'Smart card based cashless transactions.',
    ],
    documentsRequired: [
      'BPL Smart Card / Ration Card',
      'Aadhaar Card',
      'Income Certificate',
    ],
    applicationSteps: [
      'BPL lists are uploaded to the RSBY enrollment servers.',
      'Enrollment teams visit local centers to capture biometrics and photos.',
      'Pay a registration fee of ₹30 to collect the RSBY Smart Card.',
    ],
    officialLink: 'http://www.rsby.gov.in',
  },
];

// Schemes that can be applied for online, mapped to their application portal.
// Anything not listed here is applied in person (post office / bank branch / camp).
const ONLINE_APPLY = {
  'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (PM-JAY)': 'https://pmjay.gov.in/beneficiary',
  'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)': 'https://www.jansuraksha.gov.in',
  'Pradhan Mantri Suraksha Bima Yojana (PMSBY)': 'https://www.jansuraksha.gov.in',
  'Atal Pension Yojana (APY)': 'https://enps.nsdl.com',
  'Pradhan Mantri Fasal Bima Yojana (PMFBY)': 'https://pmfby.gov.in',
  'National Pension System (NPS)': 'https://enps.nsdl.com',
  'Pudhumai Penn Scheme': 'https://www.pudhumapenn.tn.gov.in',
  'Kalaignar Magalir Urimai Thittam': 'https://www.tn.gov.in',
  'Pradhan Mantri Awas Yojana - Urban (PMAY-U)': 'https://pmay-urban.gov.in',
  'Pradhan Mantri Shram Yogi Maan-dhan (PM-SYM)': 'https://maandhan.in',
  'PM Kisan Samman Nidhi (PM-KISAN)': 'https://pmkisan.gov.in',
  'Gruha Lakshmi Scheme (Karnataka)': 'https://sevasindhu.karnataka.gov.in',
  'Rythu Bandhu Scheme (Telangana)': 'https://rythubandhu.telangana.gov.in',
  'Ladli Behna Yojana (Madhya Pradesh)': 'https://cmladlibahna.mp.gov.in',
  'Kanyashree Prakalpa (West Bengal)': 'https://www.wbkanyashree.gov.in',
  'Central Sector Scheme of Scholarship for College Students': 'https://scholarships.gov.in',
  'Mukhyamantri Amrutum Yojana (MA)': 'https://magujarat.in',
  'Biju Swasthya Kalyan Yojana (BSKY)': 'https://bsky.odisha.gov.in',
  'Pradhan Mantri Matru Vandana Yojana (PMMVY)': 'https://wcd.gov.in',
  'Pradhan Mantri Jan Dhan Yojana (PMJDY)': 'https://pmjdy.gov.in',
  'Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)': 'https://nrega.nic.in',
  'Rashtriya Swasthya Bima Yojana (RSBY)': 'http://www.rsby.gov.in',
};

schemes.forEach((scheme) => {
  const applyLink = ONLINE_APPLY[scheme.name];
  scheme.applyOnline = Boolean(applyLink);
  scheme.applyLink = applyLink || '';
});

async function seed() {
  try {
    const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/finnova';
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB to seed Schemes');

    await Scheme.deleteMany();
    console.log('🗑️ Cleared existing schemes');

    await Scheme.insertMany(schemes);
    console.log(`🎉 Seeded ${schemes.length} schemes successfully`);

    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  } catch (error) {
    console.error('❌ Error seeding schemes:', error);
    process.exit(1);
  }
}

seed();
